=== insoPL/technologieZadanieGit/dane_osobowe.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="osoba">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="imie" type="xs:string"/>

        <xs:element name="nazwisko" type="xs:string"/>

        <xs:element name="plec">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="m"/>
              <xs:enumeration value="k"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>

        <xs:element name="wiek">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:minInclusive value="0"/>
              <xs:maxInclusive value="120"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== insoPL/technologieZadanieGit/dane_osobowe.xml
<?xml version="1.0" encoding="UTF-8"?>
<osoba xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="dane_osobowe.xsd">

    <imie>Adriano</imie>
    <nazwisko>Bro≈ºalski</nazwisko>
    <plec>m</plec>
    <wiek>29</wiek>

</osoba>


<osoba>
    <imie>Jan</imie>
    <nazwisko>Kowalski</nazwisko>
    <plec>m</plec>
    <wiek>25</wiek>
</osoba>
